command! -bang          NeotermOpen        call neoterm#open()
command! -bang          NeotermClose       call neoterm#close()
command! -bang          NeotermToggle      call neoterm#toggle()
command! -bang -nargs=+ NeotermRun         call neoterm#run('<args>')
command! -bang          NeotermRerun       call neoterm#rerun()
command! -bang          NeotermExit        call neoterm#exit()
