name: Checks

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  formatting:
    name: Formatting (stylua)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Check formatting
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  lint:
    name: Lint (luacheck)
    runs-on: ubuntu-latest
    steps:
      - name: Fetch code
        uses: actions/checkout@v4

      - name: Run luacheck
        uses: lunarmodules/luacheck@v1
        args:
          - lua
